//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに失われたりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Momoclo.Account
{


    public partial class ChangePassword
    {

        /// <summary>
        /// ChangeUserPassword コントロール。
        /// </summary>
        /// <remarks>
        /// 自動生成されたフィールド。
        /// 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ChangePassword ChangeUserPassword;
    }
}
