//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Momoclo
{
    #region コンテキスト
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    public partial class MomocloEDMContainer : ObjectContext
    {
        #region コンストラクター
    
        /// <summary>
        /// アプリケーション構成ファイルの 'MomocloEDMContainer' セクションにある接続文字列を使用して新しい MomocloEDMContainer オブジェクトを初期化します。
        /// </summary>
        public MomocloEDMContainer() : base("name=MomocloEDMContainer", "MomocloEDMContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい MomocloEDMContainer オブジェクトを初期化します。
        /// </summary>
        public MomocloEDMContainer(string connectionString) : base(connectionString, "MomocloEDMContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい MomocloEDMContainer オブジェクトを初期化します。
        /// </summary>
        public MomocloEDMContainer(EntityConnection connection) : base(connection, "MomocloEDMContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分メソッド
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        public ObjectSet<Member> Members
        {
            get
            {
                if ((_Members == null))
                {
                    _Members = base.CreateObjectSet<Member>("Members");
                }
                return _Members;
            }
        }
        private ObjectSet<Member> _Members;

        #endregion
        #region AddTo メソッド
    
        /// <summary>
        /// Members EntitySet に新しいオブジェクトを追加するための非推奨のメソッドです。代わりに、関連付けられている ObjectSet&lt;T&gt; プロパティの .Add メソッドを使用してください。
        /// </summary>
        public void AddToMembers(Member member)
        {
            base.AddObject("Members", member);
        }

        #endregion
    }
    

    #endregion
    
    #region エンティティ
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MomocloEDM", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region ファクトリ メソッド
    
        /// <summary>
        /// 新しい Member オブジェクトを作成します。
        /// </summary>
        /// <param name="id">ID プロパティの初期値。</param>
        /// <param name="color">Color プロパティの初期値。</param>
        /// <param name="name">Name プロパティの初期値。</param>
        /// <param name="birth">Birth プロパティの初期値。</param>
        /// <param name="bloodtype">bloodtype プロパティの初期値。</param>
        /// <param name="birthplace">birthplace プロパティの初期値。</param>
        /// <param name="height">height プロパティの初期値。</param>
        public static Member CreateMember(global::System.Int32 id, global::System.String color, global::System.String name, global::System.String birth, global::System.String bloodtype, global::System.String birthplace, global::System.String height)
        {
            Member member = new Member();
            member.ID = id;
            member.Color = color;
            member.Name = name;
            member.Birth = birth;
            member.bloodtype = bloodtype;
            member.birthplace = birthplace;
            member.height = height;
            return member;
        }

        #endregion
        #region プリミティブ プロパティ
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Birth
        {
            get
            {
                return _Birth;
            }
            set
            {
                OnBirthChanging(value);
                ReportPropertyChanging("Birth");
                _Birth = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Birth");
                OnBirthChanged();
            }
        }
        private global::System.String _Birth;
        partial void OnBirthChanging(global::System.String value);
        partial void OnBirthChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bloodtype
        {
            get
            {
                return _bloodtype;
            }
            set
            {
                OnbloodtypeChanging(value);
                ReportPropertyChanging("bloodtype");
                _bloodtype = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("bloodtype");
                OnbloodtypeChanged();
            }
        }
        private global::System.String _bloodtype;
        partial void OnbloodtypeChanging(global::System.String value);
        partial void OnbloodtypeChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String birthplace
        {
            get
            {
                return _birthplace;
            }
            set
            {
                OnbirthplaceChanging(value);
                ReportPropertyChanging("birthplace");
                _birthplace = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("birthplace");
                OnbirthplaceChanged();
            }
        }
        private global::System.String _birthplace;
        partial void OnbirthplaceChanging(global::System.String value);
        partial void OnbirthplaceChanged();
    
        /// <summary>
        /// 使用できるメタデータ ドキュメントはありません。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String height
        {
            get
            {
                return _height;
            }
            set
            {
                OnheightChanging(value);
                ReportPropertyChanging("height");
                _height = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("height");
                OnheightChanged();
            }
        }
        private global::System.String _height;
        partial void OnheightChanging(global::System.String value);
        partial void OnheightChanged();

        #endregion
    
    }

    #endregion
    
}
